version: '3.9'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - $PWD/setup-database/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Mudar.134
      - MYSQL_DATABASE=UTENTI
      - MYSQL_USER=adm_user
      - MYSQL_PASSWORD=Mudar.123
    networks:
      - gestione-degli-utenti-network

  gestione-degli-utenti-service:
    image: gabrielnegrao/gestione-degli-utenti:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: UTENTI
      DB_PASSWORD: Mudar.123
      DB_PORT: 3306
      DB_USER: adm_user
    networks:
      - gestione-degli-utenti-network

networks:
  gestione-degli-utenti-network:
    driver: bridge