spring:
  application:
    name: utenti
  datasource:
    url: jdbc:h2:mem:utentiDb
    username: adm
    password: 12345

server:
  port: ${UTENTI_APPLICATION:8080}

---
spring:
  config:
    activate:
      on-profile:
        - docker
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:UTENTI}?autoReconnectForPools=true&characterEncoding=utf8&useSSL=false
    username: ${DB_USER:adm_user}
    password: ${DB_PASSWORD:Mudar.123}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl