DROP TABLE IF EXISTS TB_UTENTI;

CREATE TABLE TB_UTENTI(
    ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    COGNOME VARCHAR(255) NOT NULL,
    MAIL VARCHAR(255) NOT NULL,
    INDIRIZZO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);